server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:
   datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/portfolio?serverTimezone=Asia/Seoul
      username: root
      password: 1234

   jpa:
      show-sql: true
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQLDialect
            format-sql: true
            default-batch-fetch-size: 1000
            id:
               use-new-id-generator-mappings: true
      hibernate:
         ddl-auto: create
         naming:
            physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
         
      
      
   mail:
      host: smtp.gmail.com
      port: 587
      username: jaedong0im@gmail.com
      password: zxprruzwjcgcqkru
      properties:
         mail:
            smtp:
               auth: true
               starttls:
                  enable: true
                  required: true
                  
auth:
  key: 1234